//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272_F4Y.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EmployeeRanges = new HashSet<EmployeeRange>();
            this.EmployeeTransports = new HashSet<EmployeeTransport>();
        }
    
        public int EmployeeID { get; set; }
        public Nullable<bool> EmployeePicture { get; set; }
        public string EmployeeJobSkill { get; set; }
        public int ProfileID { get; set; }
        public int SkillSetID { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual SkillSet SkillSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeRange> EmployeeRanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeTransport> EmployeeTransports { get; set; }
    }
}
