//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272_F4Y.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbF4Entities : DbContext
    {
        public dbF4Entities()
            : base("name=dbF4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeRange> EmployeeRanges { get; set; }
        public virtual DbSet<EmployeeTransport> EmployeeTransports { get; set; }
        public virtual DbSet<Employer> Employers { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LogIn> LogIns { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<ProfileLocation> ProfileLocations { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Required> Requireds { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<SkillSet> SkillSets { get; set; }
        public virtual DbSet<Transport> Transports { get; set; }
    }
}
